version: '3.9'

volumes:
  client-dist:
  client-dist-ssr:

services:
  postgres:
    image: postgres:15
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data

  client:
    container_name: prakticum-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - '80:80'
    volumes:
      - client-dist:/app/dist
      - client-dist-ssr:/app/dist-ssr

  server:
    container_name: prakticum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    environment:
      - IS_DOCKER_BUILD=true
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - client
      - postgres
    volumes:
      - client-dist:/app/client-dist
      - client-dist-ssr:/app/dist-ssr


