export { default as Page404 } from './404';
export { default as ErrorPage } from './ErrorPage';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Welcome } from './Welcome';
export { default as Leaderboard } from './Leaderboard';
export { default as GameMenu } from './Menu';
export { default as Settings } from './Settings';
export { default as Tutorial } from './Tutorial';
