export const demoMessage = [
  {
    id: 1,
    date: '2020-01-02T14:22:22.000Z',
    author: { id: 1, firstName: 'Иван', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 0,
    emojis: [],
    text: 'Если нажать два раза прыжок, то взлетишь',
  },
  {
    id: 2,
    date: '2020-01-02T14:27:55.000Z',
    author: { id: 2, firstName: 'Митя', secondName: 'Ликупер' },
    postId: 1,
    messageMainId: 1,
    emojis: [{ id: 1, authorId: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] }],
    text: 'Ты все врешь, я только как не нажимал, не чего не получается',
  },
  {
    id: 3,
    date: '2020-01-02T17:34:04.000Z',
    author: { id: 1, firstName: 'Иван', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 0,
    emojis: [],
    text: 'Если нажать два раза прыжок, то взлетишь',
  },
  {
    id: 4,
    date: '2020-01-02T20:01:20.000Z',
    author: { id: 1, firstName: 'Ivan', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 1,
    emojis: [
      { id: 1, authorId: [1, 2] },
      { id: 2, authorId: [1] },
    ],
    text: 'Значит ты рукожоп, у меня все норм',
  },
  {
    id: 5,
    date: '2020-01-02T20:01:20.000Z',
    author: { id: 1, firstName: 'Ivan', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 1,
    emojis: [
      { id: 1, authorId: [1, 2] },
      { id: 2, authorId: [1] },
    ],
    text: 'Значит ты рукожоп, у меня все норм',
  },
  {
    id: 6,
    date: '2020-01-02T20:01:20.000Z',
    author: { id: 1, firstName: 'Ivan', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 1,
    emojis: [
      { id: 1, authorId: [1, 2] },
      { id: 2, authorId: [1] },
    ],
    text: 'Значит ты рукожоп, у меня все норм',
  },
  {
    id: 7,
    date: '2020-01-02T20:01:20.000Z',
    author: { id: 1, firstName: 'Ivan', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 1,
    emojis: [
      { id: 1, authorId: [1, 2] },
      { id: 2, authorId: [1] },
    ],
    text: 'Значит ты рукожоп, у меня все норм',
  },
  {
    id: 8,
    date: '2020-01-02T20:01:20.000Z',
    author: { id: 1, firstName: 'Ivan', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 1,
    emojis: [
      { id: 1, authorId: [1, 2] },
      { id: 2, authorId: [1] },
    ],
    text: 'Значит ты рукожоп, у меня все норм',
  },
  {
    id: 9,
    date: '2020-01-02T20:01:20.000Z',
    author: { id: 1, firstName: 'Ivan', secondName: 'Karlson' },
    postId: 1,
    messageMainId: 1,
    emojis: [
      { id: 1, authorId: [1, 2] },
      { id: 2, authorId: [1] },
    ],
    text: 'Значит ты рукожоп, у меня все норм',
  },
];

export const demoPost = {
  id: 1,
  date: '2020-01-02T14:22:22.000Z',
  author: { id: 1, firstName: 'Ivan', secondName: 'Karlson' },
  title: 'Это новый лайвхак. Это новый лайвхак. Это новый лайвхак. Это новый лайвхак.',
};
